//
//  PlanPDF.swift
//  Gym Traker
//
//  Renders the plan as an A4 PDF: one section per day template, numbered
//  exercises with their scheme, plus the weekly schedule. Made to be printed
//  and stuck on a gym bag, so it is plain black on white, not glass.
//

import Foundation
import UIKit

enum PlanPDF {

    private static let pageSize = CGSize(width: 595, height: 842)   // A4 at 72 dpi
    private static let margin: CGFloat = 44

    private enum Style {
        static let title = UIFont.systemFont(ofSize: 26, weight: .bold)
        static let dayTitle = UIFont.systemFont(ofSize: 17, weight: .bold)
        static let body = UIFont.systemFont(ofSize: 11, weight: .regular)
        static let bodyBold = UIFont.systemFont(ofSize: 11, weight: .semibold)
        static let caption = UIFont.systemFont(ofSize: 9, weight: .regular)
        static let grey = UIColor(white: 0.42, alpha: 1)
        static let rule = UIColor(white: 0.85, alpha: 1)
    }

    /// Renders the plan and returns the file URL to share.
    static func write(plan: Plan, profile: UserProfile?, to directory: URL? = nil) throws -> URL {
        let units = profile?.units ?? .kg
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: pageSize))

        let data = renderer.pdfData { context in
            var cursor = Layout(context: context, pageSize: pageSize, margin: margin)
            cursor.beginPage()

            cursor.draw(plan.name, font: Style.title)
            cursor.space(4)
            cursor.draw(subtitle(plan: plan, profile: profile), font: Style.caption, color: Style.grey)
            cursor.space(14)

            drawWeek(plan: plan, into: &cursor)
            cursor.space(18)

            for day in plan.orderedDays {
                cursor.ensure(80)
                cursor.rule()
                cursor.space(10)
                cursor.draw("\(day.letter) · \(day.title)", font: Style.dayTitle)
                cursor.space(2)
                cursor.draw(
                    "\(day.orderedItems.count) exercises · \(day.totalSets) sets · about \(day.estimatedMinutes) min",
                    font: Style.caption, color: Style.grey
                )
                cursor.space(8)

                for item in day.orderedItems {
                    cursor.ensure(22)
                    drawItem(item, units: units, into: &cursor)
                }
                cursor.space(12)
            }

            cursor.ensure(30)
            cursor.rule()
            cursor.space(8)
            cursor.draw(
                "Generated by Gym Tracker on \(Date.now.formatted(date: .abbreviated, time: .shortened)). Weights in \(units.rawValue).",
                font: Style.caption, color: Style.grey
            )
        }

        let folder = directory ?? FileManager.default.temporaryDirectory
        let name = "\(safeFilename(plan.name)).pdf"
        let url = folder.appending(path: name)
        try data.write(to: url, options: .atomic)
        return url
    }

    // MARK: - Sections

    private static func subtitle(plan: Plan, profile: UserProfile?) -> String {
        var parts = ["\(plan.orderedDays.count) day templates"]
        let trainingDays = plan.weekAssignmentsRaw.filter { !$0.isEmpty }.count
        parts.append("\(trainingDays) sessions a week")
        if let profile, !profile.name.isEmpty { parts.insert(profile.name, at: 0) }
        return parts.joined(separator: " · ")
    }

    private static func drawWeek(plan: Plan, into cursor: inout Layout) {
        let names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        let width = (cursor.contentWidth - 6 * 6) / 7
        let top = cursor.y

        for index in 0..<7 {
            let x = cursor.left + CGFloat(index) * (width + 6)
            let letter = plan.letter(forWeekdayIndex: index)
            let box = CGRect(x: x, y: top, width: width, height: 42)

            let path = UIBezierPath(roundedRect: box, cornerRadius: 7)
            (letter == nil ? UIColor(white: 0.96, alpha: 1) : UIColor(white: 0.90, alpha: 1)).setFill()
            path.fill()
            Style.rule.setStroke()
            path.stroke()

            draw(names[index], in: CGRect(x: box.minX, y: box.minY + 6, width: box.width, height: 12),
                 font: Style.caption, color: Style.grey, centered: true)
            draw(letter ?? "—", in: CGRect(x: box.minX, y: box.minY + 20, width: box.width, height: 16),
                 font: Style.bodyBold, color: .black, centered: true)
        }
        cursor.y = top + 42
    }

    private static func drawItem(_ item: PlanItem, units: Units, into cursor: inout Layout) {
        let indexText = "\(item.order)."
        draw(indexText, in: CGRect(x: cursor.left, y: cursor.y, width: 22, height: 14),
             font: Style.bodyBold, color: .black)

        draw(item.exerciseName,
             in: CGRect(x: cursor.left + 22, y: cursor.y, width: cursor.contentWidth - 190, height: 14),
             font: Style.bodyBold, color: .black)

        let scheme = "\(item.targetSets.count) × \(item.repsSummary)"
        draw(scheme,
             in: CGRect(x: cursor.left + cursor.contentWidth - 168, y: cursor.y, width: 70, height: 14),
             font: Style.body, color: .black)

        draw(UnitFormatter.weight(item.workingWeightKg, in: units),
             in: CGRect(x: cursor.left + cursor.contentWidth - 98, y: cursor.y, width: 58, height: 14),
             font: Style.body, color: .black)

        draw(UnitFormatter.rest(item.restSeconds),
             in: CGRect(x: cursor.left + cursor.contentWidth - 40, y: cursor.y, width: 40, height: 14),
             font: Style.caption, color: Style.grey)

        cursor.y += 17
    }

    // MARK: - Drawing helpers

    private static func draw(
        _ text: String, in rect: CGRect, font: UIFont, color: UIColor, centered: Bool = false
    ) {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = centered ? .center : .natural
        paragraph.lineBreakMode = .byTruncatingTail
        text.draw(in: rect, withAttributes: [
            .font: font, .foregroundColor: color, .paragraphStyle: paragraph
        ])
    }

    private static func safeFilename(_ name: String) -> String {
        let slug = name.replacingOccurrences(of: "[^A-Za-z0-9]+", with: "-", options: .regularExpression)
            .trimmingCharacters(in: CharacterSet(charactersIn: "-"))
        return slug.isEmpty ? "gym-plan" : slug.lowercased()
    }

    /// Tracks the drawing position and starts a new page when one runs out.
    private struct Layout {
        let context: UIGraphicsPDFRendererContext
        let pageSize: CGSize
        let margin: CGFloat
        var y: CGFloat = 0

        var left: CGFloat { margin }
        var contentWidth: CGFloat { pageSize.width - margin * 2 }
        var bottom: CGFloat { pageSize.height - margin }

        mutating func beginPage() {
            context.beginPage()
            y = margin
        }

        /// Starts a new page when the next block would not fit.
        mutating func ensure(_ height: CGFloat) {
            if y + height > bottom { beginPage() }
        }

        mutating func space(_ amount: CGFloat) { y += amount }

        mutating func draw(_ text: String, font: UIFont, color: UIColor = .black) {
            let height = font.lineHeight + 2
            ensure(height)
            PlanPDF.draw(text, in: CGRect(x: left, y: y, width: contentWidth, height: height),
                         font: font, color: color)
            y += height
        }

        mutating func rule() {
            ensure(1)
            let path = UIBezierPath()
            path.move(to: CGPoint(x: left, y: y))
            path.addLine(to: CGPoint(x: left + contentWidth, y: y))
            Style.rule.setStroke()
            path.lineWidth = 0.5
            path.stroke()
            y += 1
        }
    }
}
